name: Build Repo Listing

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  release:
    types: [published, created, edited, unpublished, deleted, released]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  
# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true
  
env:
  listPublishDirectory: Website
  pathToCi: ci

jobs:
  
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3 # check out this repo

      - name: Build Package Version Listing
        run: |
          npm install --no-save got@12.5.3
          mkdir -p ${{env.listPublishDirectory}}
          node .scripts/create_index_json.mjs kurotu/MaterialReplacer package.json > ${{env.listPublishDirectory}}/index.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Setup Pages
        uses: actions/configure-pages@v2
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{env.listPublishDirectory}}
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
